compute_environment: LOCAL_MACHINE
distributed_type: DEEPSPEED
mixed_precision: fp16          # позже можно поменять на bf16
num_processes: 2
gpu_ids: 0,1
machine_rank: 0
num_machines: 1

deepspeed_config:
  train_micro_batch_size_per_gpu: 26
  zero_stage: 2
  gradient_accumulation_steps: 1
  offload_param: false
  zero3_init_flag: false
  gradient_clipping: 1.0
