defaults:
  - model: base
  - dataset: triplets
  - _self_

seed: 42
device: ${env:DEVICE,cuda}

batch:
  batch_size: 8
  num_hard_negs: 5
  ref_size: 128

training:
  epochs: 2
  lr: 1e-5
  weight_decay: 0.01
  temperature: 0.02
  ckpt_steps: 2000
  output_dir: checkpoints

wandb:
  project: ru-en-embedder-finetune
  api_key: null
  use_wandb: true

resume_from: null    # <-- путь к папке с state-00000X, например "checkpoints/step_2000"

# чтобы Hydra не создавал вложенные папки, а сохранял в cwd:
hydra:
  run:
    dir: .
