defaults:
  - model: small
  - dataset: triplets_3M
  - accelerate: default_config
  - _self_

seed: 42
device: ${env:DEVICE,cuda}

batch:
  batch_size: 52
  num_hard_negs: 5
  ref_size: 384

training:
  epochs: 1
  lr: 1e-5
  weight_decay: 0.01
  temperature: 0.02
  output_dir: saved_model

wandb:
  project: ru-en-embedder-finetune
  api_key: null #если есть ключ, ставится в os.environ, если же null, предпологается, что уже стоит в os.environ
  use_wandb: true



# чтобы Hydra не создавал вложенные папки, а сохранял в cwd:
hydra:
  run:
    dir: .
